### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by jayvdb** [pepkit/veracitools#1]
Hi, this repository doesnt have a license file, afaics.

**Comment by nsheff** [comment]
indeed, licence is specified in setup.py but we can add a file

https://github.com/pepkit/veracitools/blob/1731a241d80ec63e1033a38f13a8873be09411e9/setup.py#L46

**Comment by nsheff** [comment]
I'm not going to draft a new release for that unless you ask me to...

**Comment by jayvdb** [comment]
I dont need a new release for this.  Thanks for the quick response.

**Comment by jayvdb** [comment]
A few other repos are missing one.  Might as well solve it across the org?  e.g. https://github.com/pepkit/divvy

**Comment by jayvdb** [comment]
Also it is now recommended that the license= field in setup.py/.cfg uses a SPDX identifier, which is [`BSD-2-Clause`](https://opensource.org/licenses/BSD-2-Clause).  That allows other software to detect the license , e.g. for RPM .spec generators, automated license auditing, etc.  It doesnt seem to be common yet in R from my limited exposure there.

**Comment by nsheff** [comment]
Yeah I've been slowly adding them over the past few months. I'll try to get them all done.
Thanks for the tip on the identifier, I'll be sure to update those as well.

**Comment by jayvdb** [comment]
Great. fwiw, I am attempting to package up bulker, and of course hitting lots of other dependencies.  https://github.com/databio/logmuse/ also doesnt have a license.  I see you are a maintainer in that org also.  Lots of repos!

**Comment by nsheff** [comment]
cool, how'd you find bulker?

it's funny because I had added licences to lots of these repos a few months ago... so, some have them on dev branches, others in commits that haven't been pushed yet, etc.

**Comment by jayvdb** [comment]
I am looking at portable Python app creators/tools, and bulker popped up in my searches, and it was actually quite similar to a solution I had been think.  I think I have seen another like it, a while ago, but it looks like bulker is more advance.

btw, you might want to take a look at [`moban`](https://github.com/moremoban/moban) and especially the template-set https://github.com/moremoban/pypi-mobans , as a way to automate change-management across lots of repos with you in full control.  e.g. https://github.com/coala/coala/blob/master/.moban.yaml and https://github.com/coala/coala/blob/master/.travis.yml#L39 forces updates to be done in all repos before the repo is green again, so you can change a template and then implement it in the various repos later, and CI wont let you forget.
